// Auth Actions Types
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const HANDLE_EMAIL_SUCCESS = "HANDLE_EMAIL_SUCCESS";
export const HANDLE_EMAIL_ERROR = "HANDLE_EMAIL_ERROR";
export const HANDLE_EMAIL_CODE_ERROR = "HANDLE_EMAIL_CODE_ERROR";
export const SEND_CODE_SUCCESS = "SEND_CODE_SUCCESS";
export const RESET_MESSAGE = "RESET_MESSAGE";
export const RESET_DISCOUNT_MESSAGE = "RESET_DISCOUNT_MESSAGE";
export const RESET_ALL_MESSAGE = "RESET_ALL_MESSAGE";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";
export const GET_PLANS_SUCCESS = "GET_PLANS_SUCCESS";
export const GET_PLANS_ERROR = "GET_PLANS_ERROR";
export const GET_DISCOUNT_VALUE_SUCCESS = "GET_DISCOUNT_VALUE_SUCCESS";
export const GET_DISCOUNT_VALUE_ERROR = "GET_DISCOUNT_VALUE_ERROR";
export const HANDLE_REGISTER_ERROR = "HANDLE_REGISTER_ERROR";
export const HANDLE_IS_USER_AUTHENTICATED = "HANDLE_IS_USER_AUTHENTICATED";
export const HANDLE_LOADING_REQUEST = "HANDLE_LOADING_REQUEST";
//Step
export const UPDATE_STEP = "UPDATE_STEP";
