export const HANDLE_IS_USER_AUTHENTICATED = "HANDLE_IS_USER_AUTHENTICATED";
export const HANDLE_LOGIN_REQUEST = "HANDLE_LOGIN_REQUEST";
export const HANDLE_LOGIN_SUCCESS = "HANDLE_LOGIN_SUCCESS";
export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";
export const HANDLE_LOGIN_ERROR = "HANDLE_LOGIN_ERROR";
export const GET_SINGLE_OUTLET = "GET_SINGLE_OUTLET";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_ERROR = "FETCH_ERROR";
